### ISSUE TITLE
Better .env Support

### ISSUE THREAD

**Issue by kas-catholic** [opensourcecatholic/marriage-booklet#108]
@JohnRDOrazio What are you currently using to load your `.env` file?

Asking because while I'm familiar with `.env` files, I don't personally use them that often, so nothing loads them for me. The easiest thing for me to do was edit `config/database.yml`. But I'd prefer to make it so that (at least for dev and test) no edits are necessary and everything just works.

Some options that could get us there:

- Hard-code usernames and passwords for dev and test. It isn't hard to create the necessary users on a dev or test database, and our setup code can do this automatically. Less config to manage, fewer things that can go wrong.
- OR use values from `.env` as an override but have a fallback if they're empty.
- OR use a [gem](https://github.com/bkeepers/dotenv) to load `.env` automatically.
- OR add docs to the readme about how to set something up to load them.

I'm mostly concerned with dev and test. I like my first and second suggestions best, but I'm open to other ideas. IMO, it would be fine to use hard-coded values in dev and test and an env var in prod (assuming you don't want to commit a prod db password to the repo). Perhaps the simplest thing to do is to make `.env` act as an override and put a hard-coded fallback everywhere. Thoughts?

**Comment by kas-catholic** [comment]
I'd be happy to code up a solution for this once we decide what to do.

**Comment by JohnRDOrazio** [comment]
The `.env` file is for docker, and **docker compose** will automatically pick up values from an `.env` file.

**Comment by kas-catholic** [comment]
Yes, it did work for me with `docker-compose`. But (at least on my machine) there's no mechanism to make it work with Ruby, so for example this is broken and results in an empty username:

https://github.com/opensourcecatholic/marriage-booklet/blob/046849ce16172ea9793ebc62db88088d18cf9a96/config/database.yml#L32

**Comment by JohnRDOrazio** [comment]
If not using docker, I just add the environment variables to my bash profile:
https://github.com/opensourcecatholic/marriage-booklet#set-up-the-database

**Comment by JohnRDOrazio** [comment]
If you think that adding environment variables to the bash profile might start cluttering it up, and you prefer the usage of the `.env` file, I suppose we could use the gem you mentioned. But the simplest most straightforward approach would be to set in the bash profile, it's simple it's quick and doesn't require any configuration.

Even though a hard coded development password isn't much of a problem, I figure it's generally a best practice to try to abstract these things out of the code, just to keep good habits.
