### ISSUE TITLE
setup weblate webhooks

### ISSUE THREAD

**Issue by JohnRDOrazio** [opensourcecatholic/marriage-booklet#20]
I've created a translation project on my translation server, so as to be able to manage the translation process in a cleaner fashion. It's a weblate server which I created in the past few months for other projects I work on, and I am finding it to be quite useful and functional.

One of the advantages of weblate is that it has an API that can talk to Github. So any pushes made to github can be easily picked up by weblate. This however requires the creation of a webhook in the repository's settings, see here:

https://docs.weblate.org/en/weblate-4.6.2/admin/continuous.html#github-setup

It should be enough to add this url:
https://translate.johnromanodorazio.com/hooks/github/

(If for any reason that doesn't seem to work, maybe try just https://translate.johnromanodorazio.com , I have a vague recollection of maybe having to do this to make it work right on the last project I added.)

I set up weblate so that it will never push to **main**, it will push translations to it's own branch **weblate** and will open PR's that can then be merged to main, so that we can be sure that it will never mess up any of the project code. We will have full control over the translation process and workflow.

I'm not sure if the ability to create the **weblate** branch and push to it will require some extra permissions? We'll have to test and see.

**Comment by JohnRDOrazio** [comment]
@mkasberg could you look into this? just need to add https://translate.johnromanodorazio.com/hooks/github/ to the webhooks in the repo settings, for the `onpush` event to the main branch. That way, any time the translation files are updated here in the repo, the changes will be picked up by the translation server.

**Comment by kas-catholic** [comment]
Added the webhook, let me know if it's working and feel free to close this issue if so!

**Comment by JohnRDOrazio** [comment]
webhook is confirmed to be working! with PR #44 translation keys were added. As soon as the PR was merged, I went back over to weblate, and lo and behold the new keys were present and ready to be translated!
