### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by mftruso** [opensourcecatholic/marriage-booklet#4]
Determine the best/standard rails library to use for handling user authentication and secure storing of passwords

**Comment by kas-catholic** [comment]
Rails provides a mechanism with user authentication with [has_secure_password](https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html), and that's probably what we should use. Using this ensures you don't mess up the cryptography part. Pretty much every rails app I've seen that supports logins makes use of this.

Also documented here in Rails Guides: https://guides.rubyonrails.org/active_model_basics.html#securepassword

It's pretty flexible (only assumes that you'll have a model that stores a bcrypt password), but there are several guides for implementing basic auth (new user/login/etc routing). https://gist.github.com/iscott/4618dc0c85acb3daa5c26641d8be8d0d

**Comment by JohnRDOrazio** [comment]
I'd say that after PR #98 we can pretty much close this. Further perfectioning can still be performed but at least the basic workflow is in place.
