### ISSUE TITLE
declare required node version in `.node-version`

### ISSUE THREAD

**Issue by JohnRDOrazio** [opensourcecatholic/marriage-booklet#47]
Just as we declare the version of **ruby** required or at least used in the project through the `.ruby-version` file,  perhaps we should also declare the version of **node** that is required.

In fact, `tailwindcss@2.1.4` which we are using requires a version of node `>=12.13.0`.

Perhaps we can add some information to the wiki about how to make sure you have the right version of node installed for the project (made with **nvm** + **avm** using `.node-version`?)

**Comment by JohnRDOrazio** [comment]
Does it matter which version of `yarn` is being used? I have **v1.22.5**, and I've been using it without any problems. I see in the [yarn installation instructions](https://yarnpkg.com/getting-started/install#per-project-install) that you can set the `yarn` version on a per project basis, updating for example to a `v2` release line. Has anyone been using **yarn v2**?

**Comment by kas-catholic** [comment]
Yes, tracking the node version is a good suggestion that I hadn't got around to yet. I think #48 is good to go.

I've used Yarn 2 on one or two projects. I think it would be reasonable to upgrade to it following their instructions. IIRC it isn't terribly hard but takes a little bit of time to perform the upgrade. Not crucial but something that would be nice to have.
