### ISSUE TITLE
Google fonts not loading on production instance

### ISSUE THREAD

**Issue by JohnRDOrazio** [opensourcecatholic/marriage-booklet#51]
When accessing the production instance, I'm seeing that Google Fonts are not rendering.

Perhaps an approach for Google Fonts which can also boost performance is [this guy's suggestion](https://dev.to/andrewmcodes/instantly-speed-up-your-rails-application-by-self-hosting-your-fonts-526d), self host them using the `typeface` project in yarn.

**Comment by kas-catholic** [comment]
I'm not strongly opposed to the idea but I do like the simplicity of Google Fonts hosted by Google for a small project like this...

The fonts appear to be loading fine for me on the production instance. Do you have any network or console errors in your dev tools?

**Comment by JohnRDOrazio** [comment]
yeah you were seeing them as loading fine, because I had manually made the change in the PR already, as I was trying to figure out the problem
