### ISSUE TITLE
`assets pipeline` vs `webpack`

### ISSUE THREAD

**Issue by JohnRDOrazio** [opensourcecatholic/marriage-booklet#57]
Seeing that on the production instance, the scaffold generated stylesheet (in this case, `/app/assets/stylesheets/projects.scss`) which should apply to the generated resource (in this case `projects`), is not actually being applied:

we need to figure out how to handle the **assets pipeline** vs the **webpack** workflow when it comes to stylesheets.

Here is a good blog post about this: https://mariochavez.io/desarrollo/2020/05/19/from-the-asset-pipeline-to-webpack/

Perhaps we should try to do away with the **assets pipeline** altogether, and use only a webpack workflow? If so, how would this work for stylesheets that should apply to a whole resource (such as `projects`), and all views associated with that resource?

**Comment by kas-catholic** [comment]
I think you're on the right track here but I'll need to read up a little before I have a good answer.
