### ISSUE TITLE
possible race conditions in tests

### ISSUE THREAD

**Issue by JohnRDOrazio** [opensourcecatholic/marriage-booklet#71]
When tests run, whether locally or on Pull Requests, errors will still sometimes pop up, such as:

```
ProjectsControllerTest#test_should_create_project [/home/runner/work/marriage-booklet/marriage-booklet/test/controllers/projects_controller_test.rb:23]:
Expected response to be a redirect to <http://www.example.com/en/projects/aa67c98c-d81f-5a9c-b0bc-26caa0051aea> but was a redirect to <http://www.example.com/en/projects/4ffbf1a9-7813-4b67-a61f-43a3fa43ae50>.
Expected "http://www.example.com/en/projects/aa67c98c-d81f-5a9c-b0bc-26caa0051aea" to be === "http://www.example.com/en/projects/4ffbf1a9-7813-4b67-a61f-43a3fa43ae50".
```

This could perhaps be do to race conditions, where one test is creating a resource at the same time that another test is deleting it.

We need to look further into the cause of these errors. Perhaps some useful info here: https://blog.arkency.com/2015/09/testing-race-conditions/

**Comment by JohnRDOrazio** [comment]
Should we be using `Rspec` models and `shoulda` matchers?

See here: https://www.learnhowtoprogram.com/ruby-and-rails/rails-with-active-record/many-to-many-associations

**Comment by JohnRDOrazio** [comment]
I'm wondering if implementing [Active Record Validations](https://guides.rubyonrails.org/active_record_validations.html) would solve this...
Under section **2.9 Presence**:

> If you want to be sure that an association is present, you'll need to test whether the associated object itself is present, and not the foreign key used to map the association. This way, it is not only checked that the foreign key is not empty but also that the referenced object exists.
> 
> In order to validate associated records whose presence is required, you must specify the `:inverse_of` option for the association
> 
> _If you want to ensure that the association is both present and valid, you also need to use `validates_associated`._
> If you validate the presence of an object associated via a `has_one` or `has_many` relationship, it will check that the object is neither `blank?` nor `marked_for_destruction?`.

**Comment by kas-catholic** [comment]
Tests are passing!

This issue was not a race condition, it was due to using guids as the PK combined with not specifying an ordering in some of our tests when querying for the most recently added record. Explained in detail here and fixed in the same PR: https://github.com/opensourcecatholic/marriage-booklet/pull/107#discussion_r1064205039
