### ISSUE TITLE
Choose a CSS Framework

### ISSUE THREAD

**Issue by kas-catholic** [opensourcecatholic/marriage-booklet#9]
Rails does not come with a CSS framework, but can work with pretty much any of them.

I've worked with [Bootstrap](https://getbootstrap.com/) before and that's what I'm most familiar with. With Bootstrap, we'd probably use a "Bootstrap-style" navbar [like this](https://getbootstrap.com/docs/5.0/examples/navbar-fixed/).

Has anyone else worked with any other CSS frameworks they really liked?

I've heard a lot about [Tailwind](https://tailwindcss.com/) but never used it myself.

It's also an option to build our CSS ourselves and not use any framework, but I think the frameworks provide a lot of benefits for building things quickly (like navbars and buttons) using common patterns and for mobile responsiveness (which is hard to get right on your own).

Given all the above, would we prefer to use Bootstrap, Tailwind, or something else?

**Comment by JohnRDOrazio** [comment]
am taking a look now at tailwind, I like that it's flexible, and I like that it's dynamic with nice animations and transitions. Could be something to look into for this kind of project

**Comment by mftruso** [comment]
👍 Tailwind

**Comment by kas-catholic** [comment]
I'd be excited to give Tailwind a try too, sounds like we have some consensus there :slightly_smiling_face:
